version: '1'

services:
  main:
    build: ./main
    ports:
      - "8021:8021"
    depends_on:
      - db
  square:
    build: ./square
    ports:
      - "5010:5010"
  cube:
    build: ./cube
    ports:
      - "5020:5020"
  fibonacci:
    build: ./fibonacii
    ports:
      - "5030:5030"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
